import PDFDocument from 'pdfkit';
import { InsightsData, TimeWindow } from './insights.types';

const WINDOW_LABELS: Record<TimeWindow, string> = {
  '7d': 'Last 7 Days', '30d': 'Last 30 Days', '90d': 'Last 90 Days', all: 'All Time',
};

const writeHeader = (doc: PDFKit.PDFDocument, data: InsightsData, window: TimeWindow): void => {
  doc.fontSize(20).font('Helvetica-Bold').text('MindMirror — Emotional Wellness Report', { align: 'center' });
  doc.moveDown(0.5);
  doc.fontSize(12).font('Helvetica').text(`Name: ${data.user.name ?? data.user.email}`, { align: 'center' });
  doc.text(`Period: ${WINDOW_LABELS[window]}`, { align: 'center' });
  doc.text(`Generated: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, { align: 'center' });
  doc.moveDown(1);
};

const writeSummarySection = (doc: PDFKit.PDFDocument, summary: string, entryCount: number): void => {
  doc.fontSize(14).font('Helvetica-Bold').text('Emotional Journey Summary');
  doc.moveDown(0.3);
  doc.fontSize(10).font('Helvetica-Oblique').text(`Based on ${entryCount} journal entries`);
  doc.moveDown(0.3);
  doc.fontSize(11).font('Helvetica').text(summary, { lineGap: 4 });
  doc.moveDown(1);
};

const writeEmotionTable = (doc: PDFKit.PDFDocument, data: InsightsData): void => {
  doc.fontSize(14).font('Helvetica-Bold').text('Emotion Averages');
  doc.moveDown(0.5);
  const { anxiety, stress, happiness, anger, sadness, depression } = data.emotionAverages;
  const rows: [string, number][] = [['Anxiety', anxiety], ['Stress', stress], ['Happiness', happiness], ['Anger', anger], ['Sadness', sadness], ['Depression', depression]];
  for (const [label, value] of rows) {
    doc.fontSize(11).font('Helvetica').text(`${label}:`, { continued: true, width: 150 });
    doc.font('Helvetica-Bold').text(`  ${Math.round(value)} / 100`);
  }
  doc.moveDown(1);
};

const writeStatsSection = (doc: PDFKit.PDFDocument, data: InsightsData): void => {
  doc.fontSize(14).font('Helvetica-Bold').text('Journal Activity');
  doc.moveDown(0.5);
  const { totalEntriesInWindow, longestEntry, shortestEntry, mostActiveDayOfWeek, dominantEmotion } = data.journalStats;
  doc.fontSize(11).font('Helvetica');
  doc.text(`Total Entries: ${totalEntriesInWindow}`);
  if (longestEntry) doc.text(`Longest Entry: ${longestEntry.wordCount} words (${longestEntry.date.slice(0, 10)})`);
  if (shortestEntry) doc.text(`Shortest Entry: ${shortestEntry.wordCount} words (${shortestEntry.date.slice(0, 10)})`);
  doc.text(`Most Active Day: ${mostActiveDayOfWeek}`);
  doc.text(`Dominant Emotion: ${dominantEmotion.charAt(0).toUpperCase() + dominantEmotion.slice(1)}`);
  doc.moveDown(1);
};

const writeDisclaimer = (doc: PDFKit.PDFDocument): void => {
  doc.moveDown(1);
  doc.fontSize(9).font('Helvetica-Oblique').fillColor('#888888')
    .text('This report is generated by MindMirror for personal reflection only. It is not a clinical diagnosis or substitute for professional mental health care. If you are experiencing distress, please consult a qualified mental health professional.', { align: 'center', lineGap: 2 });
};

export const generatePdfBuffer = (data: InsightsData, summary: string, entryCount: number, window: TimeWindow): Promise<Buffer> =>
  new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const buffers: Buffer[] = [];
    doc.on('data', (chunk: Buffer) => buffers.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(buffers)));
    doc.on('error', reject);
    writeHeader(doc, data, window);
    writeSummarySection(doc, summary, entryCount);
    writeEmotionTable(doc, data);
    writeStatsSection(doc, data);
    writeDisclaimer(doc);
    doc.end();
  });
